#!/bin/bash

# set persistence option
IP_persistence="yes"
User_agent_persistence="yes"

#read posted param 
input=`dd bs=${CONTENT_LENGTH} 2>/dev/null | cat -`

authkey="%%authkey"
exchange_token_uri="https://${yourOktaDomain}/oauth2/default/v1/token"
user_info_req_uri="https://${yourOktaDomain}/oauth2/default/v1/userinfo"
redirect_uri=""
client_id=""
client_secret=""
target_claim="userinfo"

echo "Content-Type: text/html"
echo ""

# load small-shell conf
. ../def/.small_shell_conf

# load header
if [ "$IP_persistence" = "yes" ];then
  remote_addr=`echo $REMOTE_ADDR | $SED "s/:/-/g"`
fi
if [ "$User_agent_persistence" = "yes" ];then
  user_agent=`echo $HTTP_USER_AGENT | $SED "s/:/-/g" | $SED "s/ /_/g"`
fi

# IP restriction check
IP_whitelisting=%%IP_whitelisting
if [ "$IP_whitelisting" = "yes" ];then

  whitelist_chk=`${small_shell_path}/bin/meta get.IP | grep -v "NO IP RESTRICTION"`
  if [ "$whitelist_chk" ];then
    for IP in $whitelist_chk
    do
      IP=`echo $IP | $SED "s/*//g"`
      if [[ ${remote_addr} == ${IP}* ]];then
        IP_chk_flag=yes
        break
      fi
    done

    if [ ! "$IP_chk_flag" = "yes" ];then
      echo "error: your IP{$remote_addr} is not allowed to access"
      exit 1
    fi
  fi
fi

param=`date +%s`
param="$param:$RANDOM"
count=1

while [ -f ../tmp/${param} ]
do
 sleep 0.01
 count=`expr $count + 1`
 if [ $count -eq 100 ];then
   echo "error: please contact to adimin"
   exit 1
 fi
done

# parse QUERY STRING
echo $QUERY_STRING | $PHP -r "echo urldecode(file_get_contents('php://stdin'));" | tr -d \$ | tr -d \` | $SED "s/\&/\n/g" > ../tmp/${param}

# parse POST param
echo $input | $SED "s/\`//g" | $SED "s/&/\n/g" \
| $PHP -r "echo urldecode(file_get_contents('php://stdin'));"  >> ../tmp/${param}
cat ../tmp/${param} | $SED -e "s/=/=\"/1" | $SED "s/$/\"/g" | $SED "s/^\"//g" | tr -d \$ | tr -d \` > ../tmp/${param}.load

chmod 755 ../tmp/${param}.load

# load query string
.  ../tmp/${param}.load
rm  ../tmp/${param}*


# render login button if thre is no step in log for audit matter
if [ ! "$code" ];then

  # regenerate  query string
  if [ "$req" ];then
    req="?req=`echo $req`"
  fi

  if [ "$id" ];then
    id="\&id=`echo $id`"
  fi

  if [ "$message" ];then
    message="<p><b>`echo $message`<\/b><\/p>"
  fi

  # render standard login form with queyr string and messge
  cat ../def/oauth_test_auth_form.html.def | $SED "s/^ *</</g"\
  | $SED "/%%auth_form_menu/r ../def/common_parts/oauth_test_auth_form_menu" \
  | $SED "s/%%auth_form_menu//g"\
  | $SED "/%%footer/r ../def/common_parts/oauth_test_footer" \
  | $SED "/%%footer/d"\
  | $SED "s/%%message/${message}/g" \
  | $SED "s/?%%params/${req}${id}/g"
  exit 0
fi

# Oauth user check & login to the APP
if [ "$code" ];then
  urlencoded_redirect_uri=`echo -n "$redirect_uri" | $PHP -r "echo urlencode(file_get_contents('php://stdin'));"`
  base64key=`echo -n "$client_id:$client_secret" | $BASE64_ENC`

  res=`$CURl --request POST \
  --url $exchange_token_uri \
  --header "Authorization: Basic $base64key" \
  --header "Accept: application/json" \
  --header "Content-type: application/x-www-form-urlencoded" \
  --data "grant_type=authorization_code&redirect_uri=${urlencoded_redirect_uri}&code=${code}"`
  access_token=`echo "$res" | jq .access_token | $SED "s/\"//g"`

  res=`$CURL -X GET \
  -H "Authorization: Bearer ${access_token}" \
  "$user_info_req_uri"`
  user=`echo "$res" | jq .${target_claim} | $SED "s/\"//g"`

  if [ "$access_token" -a "$user" -a ! "$user" = "null" ];then
    user=`echo $user | $AWK -F"@" '{print $1}'`
    auth_req=`${small_shell_path}/bin/extension_auth app:oauth_test key_auth:${authkey} force_user:${user} remote_addr:${remote_addr} user_agent:${user_agent}`
    session=`echo $auth_req | $AWK -F "," '{print $2}' | $AWK -F ":" '{print $2}'`
    pin=`echo $auth_req | $AWK -F "," '{print $3}' | $AWK -F ":" '{print $2}'`
   
    if [ "$session" -a "$pin" ];then
      if [ ! "$req" ];then
        req=main
      fi

      # redirect to APP if key auth is OK
      if [[ $req == *table ]];then
        echo "<meta http-equiv=\"refresh\" content=\"0; url=./oauth_test?session=$session&pin=$pin&req=$req\">"
      elif [[ $req == *get ]];then
        echo "<meta http-equiv=\"refresh\" content=\"0; url=./oauth_test?session=$session&pin=$pin&req=$req&id=$id\">"
      else
        echo "<meta http-equiv=\"refresh\" content=\"0; url=./oauth_test?session=$session&pin=$pin&req=$req\">"
      fi
    fi
  else
    echo "authentication faied"
    echo "$access_token:$user"
  fi
fi

