#!/bin/bash

####################################
# controller for Scratch APP #team
####################################

# preprocedure
session_update="required"
IP_persistence="yes"
User_agent_persistence="yes"

# load small-shell params
. %%www/descriptor/.small_shell_conf

# load header
if [ "$IP_persistence" = "yes" ];then
  remote_addr=`echo $REMOTE_ADDR | $SED "s/:/-/g"`
else
  logging_IP=`echo $REMOTE_ADDR | $SED "s/:/-/g"`
fi
if [ "$User_agent_persistence" = "yes" ];then
  user_agent=`echo $HTTP_USER_AGENT | $SED "s/:/-/g" | $SED "s/ /_/g"`
fi

auth=required
param=`date +%s`
param="$param:$RANDOM"
count=1
while [ -f %%www/tmp/${param} ]
do
 sleep 0.01
 count=`expr $count + 1`
 if [ $count -eq 100 ];then
   echo "error: please contact to adimin"
   exit 1
 fi
done

# parse QUERY_STRING
echo $QUERY_STRING | $PHP -r "echo urldecode(file_get_contents('php://stdin'));" | tr -d \$ | tr -d \` | $SED "s/\&/\n/g" > %%www/tmp/${param}
cat %%www/tmp/${param} | $SED -e "s/=/=\"/1" | $SED "s/$/\"/g" | $SED "s/^\"//g" > %%www/tmp/${param}.load
chmod 755 %%www/tmp/${param}.load

# load query string
.  %%www/tmp/${param}.load
rm  %%www/tmp/${param}*

if [ ! "$req" ];then
  req=main
fi

if [ "$subapp" ];then
  if [ ! "$req" = "main" -a ! "$req" = "logout" ];then
    req="${subapp}.$req"
  fi
fi

# define contents type except statistics file or graph
if [[ ! "$req" == *stats && ! "$req" == *file ]];then
  echo "Content-Type: text/html"
  echo ""
fi

# session verification

if [ "$auth" = "required" ];then

  if [[ "$req" == *log_viewer || "$req" == *csv || "$req" == *hash || "$req" == *stats || "$req" == *file ]];then
    session_update=no

    # session check
    session_chk=`${small_shell_path}/bin/extension_auth app:team session_chk:${session} pin:${pin} \
    remote_addr:${remote_addr} user_agent:${user_agent} logging_IP:${logging_IP}`
    if [ ! "$session_chk" ];then
      if [ "$req" = "log_viewer" ];then
        echo "<meta http-equiv=\"refresh\" content=\"0; url=./auth.team?req=$req&id=$id&message=!%20Session%20Expired\">"
        exit 1
      else
        echo "<meta http-equiv=\"refresh\" content=\"0; url=./auth.team?req=$req&message=!%20Session%20Expired\">"
        exit 1
      fi
    fi
  fi

  if [ "$req" = "logout" ]; then
    ${small_shell_path}/bin/extension_auth app:team pin:${pin} remote_addr:${remote_addr} logout:${session} \
    user_agent:${user_agent} logging_IP:${logging_IP}
    echo "<meta http-equiv=\"refresh\" content=\"0; url=./auth.team?req=main\">"
    exit 0
  fi

  # session update
  if [ "$session_update" = "required" ];then
    get_session=`${small_shell_path}/bin/extension_auth session_persist:${session} \
    pin:${pin} remote_addr:${remote_addr} user_agent:${user_agent} app:team logging_IP:${logging_IP}`

    user_name=`echo $get_session | $AWK -F "," '{print $1}' | $AWK -F ":" '{print $2}'`
    session=`echo $get_session | $AWK -F "," '{print $2}' | $AWK -F ":" '{print $2}'`
    pin=`echo $get_session | $AWK -F "," '{print $3}' | $AWK -F ":" '{print $2}'`

    if [ ! "$user_name" -o ! "$session" -o ! "${pin}" ];then
      if [[ $req == *table ]];then
        echo "<meta http-equiv=\"refresh\" content=\"0; url=./auth.team?req=$req&page=$page&message=!%20Session%20Expired\">"
        exit 1
      elif [[ $req == *get ]];then
        echo "<meta http-equiv=\"refresh\" content=\"0; url=./auth.team?req=$req&id=$id&message=!%20Session%20Expired\">"
        exit 1
      else
        req=main
        echo "<meta http-equiv=\"refresh\" content=\"0; url=./auth.team?req=$req&message=!%20Session%20Expired\">"
        exit 1
      fi
    fi

    if [ "$replica_hosts" ];then
      for replica in $replica_hosts
      do
        ${small_shell_path}/bin/extension_auth app:team sync:${session}@${replica} > /dev/null 2>&1 &
      done
    fi

  fi
fi


# parse POST data
if [ "`echo $REQUEST_METHOD | grep -i "POST"`" ];then

  if [ "`echo $CONTENT_TYPE | grep "application/json"`" ];then
    method=json
  elif [ "`echo $CONTENT_TYPE | grep "multipart/form-data"`" ];then
    method=multipart
  elif [ "`echo $CONTENT_TYPE | grep "application/octet-stream"`" ];then
    method=data-binary
  else
    method=urlenc
  fi

  mkdir %%www/tmp/$session
  # dump posted data
  dd bs=${CONTENT_LENGTH} of=%%www/tmp/$session/input 2>/dev/null
  %%www/bin/parse.sh $session $method

fi

# put space to table_command
table_command="`echo $table_command | $SED "s/ /{%%space}/g"`"

#----------------------------
# routing to action scripts
#----------------------------

case "$req" in
  
  "main")
    %%www/bin/team_main.sh session:$session pin:$pin user_name:$user_name remote_addr:${remote_addr};;

  "get")
    if [ ! "$master" ];then
      %%www/bin/team_get.sh session:$session pin:$pin user_name:$user_name id:$id 
    else
      sync=`${small_shell_path}/bin/extension_auth app:team sync:${session}@${master}`
      if [ "$sync" = "synced" ];then
        redirect=yes
      else
        redirect=no
      fi
      %%www/bin/team_get.sh session:$session pin:$pin user_name:$user_name id:$id redirect:$redirect
    fi
    ;;

  "set")
    %%www/bin/team_set.sh session:$session pin:$pin user_name:$user_name databox:$databox id:$id ;;

  "table")
    %%www/bin/team_table.sh session:$session pin:$pin user_name:$user_name id:$id page:$page table_command:$table_command line:$line;;

  "log_viewer")
    %%www/bin/team_log_viewer.sh databox:$databox session:$session pin:$pin id:$id ;;

  "file")
    %%www/bin/team_dl.sh session:$session pin:$pin id:$id databox:$databox ;;

  "del")
    %%www/bin/team_del.sh session:$session pin:$pin user_name:$user_name id:$id ;;

   #--------------------------------
   # sub app routing section

   # bookmark
   "bookmarks.table") 
     %%www/bin/bookmarks_table.sh session:$session pin:$pin user_name:$user_name page:$page table_command:$table_command line:$line;;

   "bookmarks.get") 
     if [ ! "$master" ];then
       %%www/bin/bookmarks_get.sh session:$session pin:$pin user_name:$user_name id:$id 
     else
       sync=`${small_shell_path}/bin/extension_auth app:team sync:${session}@${master}`
       if [ "$sync" = "synced" ];then
         redirect=yes
       else
         redirect=no
       fi
       %%www/bin/bookmarks_get.sh session:$session pin:$pin user_name:$user_name id:$id redirect:$redirect
     fi
     ;;

   "bookmarks.set") 
     %%www/bin/bookmarks_set.sh session:$session pin:$pin user_name:$user_name id:$id ;;

   "bookmarks.del") 
     %%www/bin/bookmarks_del.sh session:$session pin:$pin user_name:$user_name id:$id ;;

   "bookmarks.log_viewer") 
     %%www/bin/bookmarks_log_viewer.sh session:$session pin:$pin id:$id ;;
 
   # drive
   "drive.table") 
     %%www/bin/drive_table.sh session:$session pin:$pin user_name:$user_name page:$page table_command:$table_command line:$line;;

   "drive.get") 
     if [ ! "$master" ];then
       %%www/bin/drive_get.sh session:$session pin:$pin user_name:$user_name id:$id
     else
       sync=`${small_shell_path}/bin/extension_auth app:team sync:${session}@${master}`
       if [ "$sync" = "synced" ];then
         redirect=yes
       else
         redirect=no
       fi
       %%www/bin/drive_get.sh session:$session pin:$pin user_name:$user_name id:$id redirect:$redirect
     fi
     ;;

   "drive.set") 
     %%www/bin/drive_set.sh session:$session pin:$pin user_name:$user_name id:$id ;;

   "drive.del") 
     %%www/bin/drive_del.sh session:$session pin:$pin user_name:$user_name id:$id ;;

   "drive.log_viewer") 
     %%www/bin/drive_log_viewer.sh session:$session pin:$pin id:$id ;;

   "drive.file") 
     %%www/bin/drive_dl.sh session:$session pin:$pin id:$id ;;

   # tasks
   "tasks.table") 
     %%www/bin/tasks_table.sh session:$session pin:$pin user_name:$user_name page:$page table_command:$table_command line:$line;;

   "tasks.get") 
     if [ ! "$master" ];then
       %%www/bin/tasks_get.sh session:$session pin:$pin user_name:$user_name id:$id
     else
       sync=`${small_shell_path}/bin/extension_auth app:team sync:${session}@${master}`
       if [ "$sync" = "synced" ];then
         redirect=yes
       else
         redirect=no
       fi
       %%www/bin/tasks_get.sh session:$session pin:$pin user_name:$user_name id:$id redirect:$redirect
     fi
     ;;

   "tasks.set")
     %%www/bin/tasks_set.sh session:$session pin:$pin user_name:$user_name id:$id ;;

   "tasks.del") 
     %%www/bin/tasks_del.sh session:$session pin:$pin user_name:$user_name id:$id ;;

   "tasks.log_viewer") 
     %%www/bin/tasks_log_viewer.sh session:$session pin:$pin id:$id ;;
  
   # inquiries
   "inquiries.table") 
     %%www/bin/inquiries_table.sh session:$session pin:$pin user_name:$user_name page:$page table_command:$table_command line:$line;;

   "inquiries.get") 
     if [ ! "$master" ];then
       %%www/bin/inquiries_get.sh session:$session pin:$pin user_name:$user_name id:$id 
     else
       sync=`${small_shell_path}/bin/extension_auth app:team sync:${session}@${master}`
       if [ "$sync" = "synced" ];then
         redirect=yes
       else
         redirect=no
       fi
       %%www/bin/inquiries_get.sh session:$session pin:$pin user_name:$user_name id:$id redirect:$redirect
     fi
     ;;

   "inquiries.set") 
     %%www/bin/inquiries_set.sh session:$session pin:$pin user_name:$user_name id:$id ;;

   "inquiries.log_viewer")
     %%www/bin/inquiries_log_viewer.sh session:$session pin:$pin id:$id ;;

   # announcements
   "announcements.table") 
     %%www/bin/announcements_table.sh session:$session pin:$pin user_name:$user_name page:$page table_command:$table_command line:$line;;

   "announcements.get") 
     if [ ! "$master" ];then
       %%www/bin/announcements_get.sh session:$session pin:$pin user_name:$user_name id:$id
     else
       sync=`${small_shell_path}/bin/extension_auth app:team sync:${session}@${master}`
       if [ "$sync" = "synced" ];then
         redirect=yes
       else
         redirect=no
       fi
       %%www/bin/announcements_get.sh session:$session pin:$pin user_name:$user_name id:$id redirect:$redirect
     fi
     ;;

   "announcements.set") 
     %%www/bin/announcements_set.sh session:$session pin:$pin user_name:$user_name id:$id;;

   "announcements.del") 
     %%www/bin/announcements_del.sh session:$session pin:$pin user_name:$user_name id:$id ;;

   "announcements.log_viewer")
     %%www/bin/announcements_log_viewer.sh session:$session pin:$pin id:$id;;

   #--------------------------------

  *)
    echo "error: wrong request";;

esac

exit 0
