#!/bin/bash

# preprocedure
session_update="required"

# load small-shell params
. %%www/descriptor/.small_shell_conf

# load remote addr
remote_addr=`echo $REMOTE_ADDR | $SED "s/:/-/g"`

IP_whitelisting=%%IP_whitelisting
auth=required

# IP restriction check
if [ "$IP_whitelisting" = "yes" ];then
  whitelist_chk=`${small_shell_path}/bin/meta get.IP | grep -v "NO IP RESTRICTION"`
  if [ "$whitelist_chk" ];then
    for IP in $whitelist_chk
    do
      IP=`echo $IP | $SED "s/*//g"`
      if [[ ${remote_addr} == ${IP}* ]];then
        IP_chk=yes
        break
      fi
    done
   
    if [ ! "$IP_chk" = "yes" ];then
      echo "error: your IP is not allowed to access"
      exit 1
    fi
  fi
fi

param=`date +%s`
param="$param:$RANDOM"
count=1
while [ -f %%www/tmp/${param} ]
do
 sleep 0.01
 count=`expr $count + 1`
 if [ $count -eq 100 ];then
   echo "error: please contact to adimin"
   exit 1
 fi
done

# parse QUERY_STRING
echo $QUERY_STRING | $PHP -r "echo urldecode(file_get_contents('php://stdin'));" | tr -d \$ | tr -d \` | $SED "s/\&/\n/g" > %%www/tmp/${param}
cat %%www/tmp/${param} | $SED -e "s/=/=\"/1" | $SED "s/$/\"/g" | $SED "s/^\"//g" > %%www/tmp/${param}.load
chmod 755 %%www/tmp/${param}.load

# load query string
.  %%www/tmp/${param}.load
rm  %%www/tmp/${param}*

if [ ! "$req" ];then
  req=main
fi

if [ "$subapp" ];then
  if [ ! "$req" = "main" -a ! "$req" = "logout" ];then
    req="${subapp}.$req"
  fi
fi

# define contents type except statistics file or graph
if [[ ! "$req" == *stats && ! "$req" == *file ]];then
  echo "Content-Type: text/html"
  echo ""
fi

# session verification

if [ "$auth" = "required" ];then

  if [[ "$req" == *log_viewer || "$req" == *csv || "$req" == *hash || "$req" == *stats || "$req" == *file ]];then
    session_update=no

    # session check
    session_chk=`sudo -u small-shell ${small_shell_path}/bin/extension_auth app:team session_chk:${session} pin:${pin} remote_addr:${remote_addr}`
    session_ip=`echo $session_chk | $AWK -F ":" '{print $2}'`

    if [ ! "${session_ip}" = ${remote_addr} ];then
      if [[ ! "$req" == *stats && ! "$req" == *file ]];then
        echo "Content-Type: text/html"
        echo ""
      fi
      echo "<meta http-equiv=\"refresh\" content=\"0; url=./auth.team?req=$req&message=!%20Session%20ExpiredDDD\">"
      exit 1
    fi
  fi

  if [ "$req" = "logout" ]; then
    sudo -u small-shell ${small_shell_path}/bin/extension_auth app:team pin:${pin} remote_addr:${remote_addr} logout:${session}
    echo "<meta http-equiv=\"refresh\" content=\"0; url=./auth.team?req=main\">"
    exit 0
  fi

  # session update
  if [ "$session_update" = "required" ];then
    get_session=`sudo -u small-shell ${small_shell_path}/bin/extension_auth session_persist:${session} \
    pin:${pin} remote_addr:${remote_addr} app:team`

    user_name=`echo $get_session | $AWK -F "," '{print $1}' | $AWK -F ":" '{print $2}'`
    session=`echo $get_session | $AWK -F "," '{print $2}' | $AWK -F ":" '{print $2}'`
    pin=`echo $get_session | $AWK -F "," '{print $3}' | $AWK -F ":" '{print $2}'`

    if [ ! "$user_name" -o ! "$session" -o ! "${pin}" ];then
      if [[ $req == *table ]];then
        echo "<meta http-equiv=\"refresh\" content=\"0; url=./auth.team?req=$req&page=$page&message=!%20Session%20Expired\">"
        exit 1
      elif [[ $req == *get ]];then
        echo "<meta http-equiv=\"refresh\" content=\"0; url=./auth.team?req=$req&id=$id&message=!%20Session%20Expired\">"
        exit 1
      else
        req=main
        echo "<meta http-equiv=\"refresh\" content=\"0; url=./auth.team?req=$req&message=!%20Session%20Expired\">"
        exit 1
      fi
    fi
  fi
fi


# parse POST data
if [ "`echo $REQUEST_METHOD | grep -i "POST"`" ];then

  if [ "`echo $CONTENT_TYPE | grep "application/json"`" ];then
    method=json
  elif [ "`echo $CONTENT_TYPE | grep "multipart/form-data"`" ];then
    method=multipart
  elif [ "`echo $CONTENT_TYPE | grep "application/octet-stream"`" ];then
    method=data-binary
  else
    method=urlenc
  fi

  mkdir %%www/tmp/$session
  # dump posted data
  dd bs=${CONTENT_LENGTH} of=%%www/tmp/$session/input 2>/dev/null
  %%www/bin/parse.sh $session $method

fi

# put space to table_command
table_command="`echo $table_command | $SED "s/ /{%%space}/g"`"

#----------------------------
# routing to action scripts
#----------------------------

case "$req" in
  
  "main")
    %%www/bin/team_main.sh session:$session pin:$pin user_name:$user_name remote_addr:${remote_addr};;

  "get")
    %%www/bin/team_get.sh session:$session pin:$pin user_name:$user_name databox:$databox id:$id ;;

  "set")
    %%www/bin/team_set.sh session:$session pin:$pin user_name:$user_name databox:$databox id:$id ;;

  "table")
    %%www/bin/team_table.sh session:$session pin:$pin user_name:$user_name id:$id page:$page table_command:$table_command line:$line;;

  "log_viewer")
    %%www/bin/team_log_viewer.sh databox:$databox session:$session pin:$pin id:$id ;;

  "file")
    %%www/bin/team_dl.sh session:$session pin:$pin id:$id databox:$databox ;;

  "del")
    %%www/bin/team_del.sh session:$session pin:$pin user_name:$user_name id:$id ;;


  # bookmark
  "bookmarks.table") %%www/bin/bookmarks_table.sh session:$session pin:$pin user_name:$user_name page:$page table_command:$table_command line:$line;;
  "bookmarks.get") %%www/bin/bookmarks_get.sh session:$session pin:$pin user_name:$user_name id:$id ;;
  "bookmarks.set") %%www/bin/bookmarks_set.sh session:$session pin:$pin user_name:$user_name id:$id ;;
  "bookmarks.del") %%www/bin/bookmarks_del.sh session:$session pin:$pin user_name:$user_name id:$id ;;
  "bookmarks.log_viewer") %%www/bin/bookmarks_log_viewer.sh session:$session pin:$pin id:$id ;;
 
  # drive
  "drive.table") %%www/bin/drive_table.sh session:$session pin:$pin user_name:$user_name page:$page table_command:$table_command line:$line;;
  "drive.get") %%www/bin/drive_get.sh session:$session pin:$pin user_name:$user_name id:$id ;;
  "drive.set") %%www/bin/drive_set.sh session:$session pin:$pin user_name:$user_name id:$id ;;
  "drive.del") %%www/bin/drive_del.sh session:$session pin:$pin user_name:$user_name id:$id ;;
  "drive.log_viewer") %%www/bin/drive_log_viewer.sh session:$session pin:$pin id:$id ;;
  "drive.file") %%www/bin/drive_dl.sh session:$session pin:$pin id:$id ;;

  # tasks
  "tasks.table") %%www/bin/tasks_table.sh session:$session pin:$pin user_name:$user_name page:$page table_command:$table_command line:$line;;
  "tasks.get") %%www/bin/tasks_get.sh session:$session pin:$pin user_name:$user_name id:$id ;;
  "tasks.set") %%www/bin/tasks_set.sh session:$session pin:$pin user_name:$user_name id:$id ;;
  "tasks.log_viewer") %%www/bin/tasks_log_viewer.sh session:$session pin:$pin id:$id ;;
  
  # inquiries
  "inquiries.table") %%www/bin/inquiries_table.sh session:$session pin:$pin user_name:$user_name page:$page table_command:$table_command line:$line;;
  "inquiries.get") %%www/bin/inquiries_get.sh session:$session pin:$pin user_name:$user_name id:$id ;;
  "inquiries.set") %%www/bin/inquiries_set.sh session:$session pin:$pin user_name:$user_name id:$id ;;
  "inquiries.log_viewer") %%www/bin/inquiries_log_viewer.sh session:$session pin:$pin id:$id ;;

  # announcements
  "announcements.table") %%www/bin/announcements_table.sh session:$session pin:$pin user_name:$user_name page:$page table_command:$table_command line:$line;;
  "announcements.get") %%www/bin/announcements_get.sh session:$session pin:$pin user_name:$user_name id:$id;;
  "announcements.set") %%www/bin/announcements_set.sh session:$session pin:$pin user_name:$user_name id:$id;;
  "announcements.del") %%www/bin/announcements_del.sh session:$session pin:$pin user_name:$user_name id:$id ;;
  "announcements.log_viewer") %%www/bin/announcements_log_viewer.sh session:$session pin:$pin id:$id;;

  *)
    echo "error: wrong request";;

esac

exit 0
